[package]
name = "order-discount"
version = "1.0.0"
edition = "2021"
rust-version = "1.62"

[dependencies]
serde = { version = "1.0.13", features = ["derive"] }
serde_json = "1.0"
shopify_function = "0.8.0"
graphql_client = "0.14.0"
aes = "0.7"
block-modes = "0.8"
base64 = "0.13"
hex = "0.4"

[profile.release]
lto = true
opt-level = 'z'
strip = true
